"""
Constants for the email campaign application
"""

# Campaign Statuses
CAMPAIGN_STATUS_DRAFT = "draft"
CAMPAIGN_STATUS_SCHEDULED = "scheduled"
CAMPAIGN_STATUS_SENDING = "sending"
CAMPAIGN_STATUS_PAUSED = "paused"
CAMPAIGN_STATUS_COMPLETED = "completed"
CAMPAIGN_STATUS_FAILED = "failed"
CAMPAIGN_STATUS_CANCELLED = "cancelled"

CAMPAIGN_STATUSES = [
    CAMPAIGN_STATUS_DRAFT,
    CAMPAIGN_STATUS_SCHEDULED,
    CAMPAIGN_STATUS_SENDING,
    CAMPAIGN_STATUS_PAUSED,
    CAMPAIGN_STATUS_COMPLETED,
    CAMPAIGN_STATUS_FAILED,
    CAMPAIGN_STATUS_CANCELLED,
]

# Recipient Statuses
RECIPIENT_STATUS_PENDING = "pending"
RECIPIENT_STATUS_SENDING = "sending"
RECIPIENT_STATUS_SENT = "sent"
RECIPIENT_STATUS_FAILED = "failed"
RECIPIENT_STATUS_BOUNCED = "bounced"
RECIPIENT_STATUS_UNSUBSCRIBED = "unsubscribed"

RECIPIENT_STATUSES = [
    RECIPIENT_STATUS_PENDING,
    RECIPIENT_STATUS_SENDING,
    RECIPIENT_STATUS_SENT,
    RECIPIENT_STATUS_FAILED,
    RECIPIENT_STATUS_BOUNCED,
    RECIPIENT_STATUS_UNSUBSCRIBED,
]

# Email Event Types
EVENT_TYPE_SENT = "sent"
EVENT_TYPE_DELIVERED = "delivered"
EVENT_TYPE_OPENED = "opened"
EVENT_TYPE_CLICKED = "clicked"
EVENT_TYPE_BOUNCED = "bounced"
EVENT_TYPE_HARD_BOUNCE = "hard_bounce"
EVENT_TYPE_SOFT_BOUNCE = "soft_bounce"
EVENT_TYPE_FAILED = "failed"
EVENT_TYPE_UNSUBSCRIBED = "unsubscribed"
EVENT_TYPE_SPAM_REPORT = "spam_report"

EMAIL_EVENT_TYPES = [
    EVENT_TYPE_SENT,
    EVENT_TYPE_DELIVERED,
    EVENT_TYPE_OPENED,
    EVENT_TYPE_CLICKED,
    EVENT_TYPE_BOUNCED,
    EVENT_TYPE_HARD_BOUNCE,
    EVENT_TYPE_SOFT_BOUNCE,
    EVENT_TYPE_FAILED,
    EVENT_TYPE_UNSUBSCRIBED,
    EVENT_TYPE_SPAM_REPORT,
]

EMAIL_PROVIDER_SMTP = "smtp"
EMAIL_PROVIDERS = [EMAIL_PROVIDER_SMTP]

# Default Template Variables
DEFAULT_TEMPLATE_VARIABLES = [
    "firstname",
    "lastname",
    "company",
    "email",
    "subject",
    "unsubscribe_url",
]

# Email Validation Regex
EMAIL_REGEX = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

# CSV Import
CSV_MAX_FILE_SIZE = 10 * 1024 * 1024  # 10 MB
CSV_PREVIEW_ROWS = 10
CSV_SUPPORTED_ENCODINGS = ["utf-8", "iso-8859-1", "windows-1252"]

# Rate Limiting
DEFAULT_BATCH_SIZE = 100
DEFAULT_RATE_LIMIT_PER_SECOND = 10
MAX_BATCH_SIZE = 1000
MAX_RATE_LIMIT_PER_SECOND = 100

# Retry Configuration
DEFAULT_MAX_RETRY_ATTEMPTS = 3
RETRY_BACKOFF_FACTOR = 2  # Exponential backoff multiplier

# Campaign Limits
MAX_CAMPAIGN_NAME_LENGTH = 255
MAX_SUBJECT_LENGTH = 500
MAX_HTML_CONTENT_SIZE = 1024 * 1024  # 1 MB
MAX_RECIPIENTS_PER_CAMPAIGN = 1000000  # 1 million

# Template Categories
TEMPLATE_CATEGORY_MARKETING = "marketing"
TEMPLATE_CATEGORY_NEWSLETTER = "newsletter"
TEMPLATE_CATEGORY_TRANSACTIONAL = "transactional"
TEMPLATE_CATEGORY_ANNOUNCEMENT = "announcement"
TEMPLATE_CATEGORY_WELCOME = "welcome"
TEMPLATE_CATEGORY_OTHER = "other"

TEMPLATE_CATEGORIES = [
    TEMPLATE_CATEGORY_MARKETING,
    TEMPLATE_CATEGORY_NEWSLETTER,
    TEMPLATE_CATEGORY_TRANSACTIONAL,
    TEMPLATE_CATEGORY_ANNOUNCEMENT,
    TEMPLATE_CATEGORY_WELCOME,
    TEMPLATE_CATEGORY_OTHER,
]

# HTTP Headers
HEADER_LIST_UNSUBSCRIBE = "List-Unsubscribe"
HEADER_LIST_UNSUBSCRIBE_POST = "List-Unsubscribe-Post"

# Compliance
GDPR_DATA_RETENTION_DAYS = 365 * 2  # 2 years
UNSUBSCRIBE_PROCESSING_DELAY_SECONDS = 0  # Immediate

# Timeouts
EMAIL_SEND_TIMEOUT_SECONDS = 30
API_REQUEST_TIMEOUT_SECONDS = 60

# Pagination
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 100
